name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m pip install poetry
        poetry config virtualenvs.in-project true
        poetry install

    - name: Run mypy
      run: make mypy

